
NUMBERS_OF_CAR_ALLOWED_TO_PARKING     = 10
PAYMENT_FOR_ONE_HOUR_IN_EURO          = 1
ADDITIONAL_PENALTY_IN_EURO            = 0.5
FREE_MINUTES_ON_THE_PARK              = 15
MINUTES_TO_LEAVE_AFTER_PAYING         = 30 